### ISSUE TITLE
Change symbol for cases

### ISSUE THREAD

**Issue by sens** [senresearch/DiseaseOutbreak-dev.jl#1]
The symbol for plotting case numbers is a square.  This is like the paper, but in my opinion looks ugly.  Can we make it smaller or use another symbol for plotting the number of cases?

**Comment by GregFa** [comment]
Absolutely, just tell me what you have in mind and I will change it. The
link blow shows all different symbol design, in case you want something
specific (other than bullet point). Tell me what color, solid or empty. I
will decrease the size too.

https://matplotlib.org/3.2.1/api/markers_api.html

Gregory.

**Comment by sens** [comment]
I think the usual dot/bullet would be fine in my opinion.
